import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#8fd6a9",
        "on-background": "#1c1b1b",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "secondary-container": "#fe6b00",
        "tertiary-fixed": "#aaf2c4",
        "secondary-fixed-dim": "#ffb693",
        "secondary": "#a04100",
        "on-primary-container": "#858383",
        "on-error-container": "#93000a",
        "tertiary": "#000000",
        "background": "#fdf8f8",
        "on-tertiary": "#ffffff",
        "outline": "#747878",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e5e2e1",
        "on-error": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "on-secondary-fixed": "#351000",
        "on-primary-fixed": "#1c1b1b",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#005230",
        "on-tertiary-fixed": "#002110",
        "on-secondary-container": "#572000",
        "on-surface-variant": "#444748",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#c8c6c5",
        "surface-container-low": "#f7f3f2",
        "tertiary-container": "#002110",
        "secondary-fixed": "#ffdbcc",
        "surface-bright": "#fdf8f8",
        "on-primary-fixed-variant": "#474746",
        "primary-fixed": "#e5e2e1",
        "surface-container": "#f1edec",
        "on-surface": "#1c1b1b",
        "primary": "#000000",
        "on-secondary-fixed-variant": "#7a3000",
        "surface": "#fdf8f8",
        "surface-tint": "#5f5e5e",
        "outline-variant": "#c4c7c7",
        "inverse-primary": "#c8c6c5",
        "inverse-surface": "#313030",
        "primary-container": "#1c1b1b",
        "surface-container-high": "#ebe7e6",
        "inverse-on-surface": "#f4f0ef",
        "surface-dim": "#ddd9d8",
        "on-tertiary-container": "#4c9169",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "section-y-lg": "220px",
        "section-y-md": "160px",
        "grid-gutter": "32px",
        "grid-margin": "80px",
      },
      fontFamily: {
        "section-title": ["Montserrat", "sans-serif"],
        "label-caps": ["Montserrat", "sans-serif"],
        "label-std": ["Montserrat", "sans-serif"],
        "hero-lg": ["Montserrat", "sans-serif"],
        "section-title-mobile": ["Montserrat", "sans-serif"],
        "stat-xl": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "hero-lg-mobile": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "section-title": ["64px", { lineHeight: "110%", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-caps": ["13px", { lineHeight: "100%", letterSpacing: "0.1em", fontWeight: "600" }],
        "label-std": ["13px", { lineHeight: "140%", fontWeight: "500" }],
        "hero-lg": ["96px", { lineHeight: "100%", letterSpacing: "-0.03em", fontWeight: "700" }],
        "section-title-mobile": ["32px", { lineHeight: "120%", fontWeight: "600" }],
        "stat-xl": ["120px", { lineHeight: "110%", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "160%", letterSpacing: "0em", fontWeight: "400" }],
        "hero-lg-mobile": ["48px", { lineHeight: "110%", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      maxWidth: {
        "site": "1440px",
      }
    },
  },
  plugins: [],
};

export default config;
